events {}

http {
   server {
      listen 80 default_server;
      listen [::]:80 default_server;
      ssi on;
      proxy_intercept_errors on;
      
      location /advisor {
          rewrite ^/advisor(.*) /$1 break;
          proxy_pass http://advisor;
      }

      location /customer {
          rewrite ^/customer(.*) /$1 break;
          proxy_pass http://customer;
      }

      location /auth {
          rewrite ^/auth(.*) /$1 break;
          proxy_pass http://auth;
      }

  }
}